/**
 * Syntax colouring for printed code blocks.
 *
 * The editor colours code with a `HighlightStyle`, whose class names are
 * generated by StyleModule at runtime — useful on screen, useless in a
 * stylesheet. So this maps the same Lezer tags onto stable `tok-*` names that
 * `print.css` can paint from the `--code-*` ramp, and both ends stay legible.
 *
 * Languages come from `@codemirror/language-data`, which the app already
 * depends on and which loads a mode only when a fence actually names it — a
 * note with one Python block should not pull in twenty grammars.
 */

import { LanguageDescription } from '@codemirror/language'
import { languages } from '@codemirror/language-data'
import { highlightCode, tagHighlighter, tags } from '@lezer/highlight'

const printHighlighter = tagHighlighter([
  { tag: [tags.keyword, tags.moduleKeyword, tags.controlKeyword], class: 'tok-keyword' },
  { tag: [tags.string, tags.special(tags.string), tags.regexp, tags.escape], class: 'tok-string' },
  { tag: [tags.number, tags.bool, tags.null, tags.atom], class: 'tok-number' },
  {
    tag: [tags.comment, tags.lineComment, tags.blockComment, tags.docComment],
    class: 'tok-comment'
  },
  {
    tag: [
      tags.function(tags.variableName),
      tags.function(tags.propertyName),
      tags.definition(tags.variableName),
      tags.macroName
    ],
    class: 'tok-function'
  },
  {
    tag: [
      tags.typeName,
      tags.className,
      tags.namespace,
      tags.standard(tags.typeName),
      tags.definition(tags.typeName)
    ],
    class: 'tok-type'
  },
  { tag: [tags.propertyName, tags.attributeName], class: 'tok-property' },
  { tag: [tags.variableName, tags.labelName], class: 'tok-variable' },
  {
    tag: [tags.operator, tags.punctuation, tags.separator, tags.bracket, tags.derefOperator],
    class: 'tok-operator'
  },
  { tag: [tags.tagName, tags.angleBracket], class: 'tok-keyword' },
  { tag: [tags.meta, tags.processingInstruction], class: 'tok-comment' },
  { tag: tags.link, class: 'tok-link' },
  { tag: tags.invalid, class: 'tok-invalid' }
])

/** One grammar per language name, so a repeated fence loads nothing twice. */
const loaded = new Map<string, Promise<LanguageDescription | null>>()

function grammarFor(name: string): Promise<LanguageDescription | null> {
  const cached = loaded.get(name)
  if (cached) return cached

  const description = LanguageDescription.matchLanguageName(languages, name, true)
  const pending: Promise<LanguageDescription | null> = description
    ? description.load().then(
        () => description,
        // An unavailable grammar is not worth failing an export over; the block
        // still prints, just in one colour.
        () => null
      )
    : Promise.resolve(null)
  loaded.set(name, pending)
  return pending
}

function escape(text: string): string {
  return text.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
}

export async function highlight(root: HTMLElement): Promise<void> {
  const blocks = Array.from(root.querySelectorAll<HTMLElement>('pre.md-code[data-lang]'))

  for (const block of blocks) {
    const name = block.dataset.lang
    const code = block.querySelector('code')
    if (!name || !code) continue

    const description = await grammarFor(name)
    const parser = description?.support?.language.parser
    if (!parser) continue

    const source = code.textContent ?? ''
    const out: string[] = []
    highlightCode(
      source,
      parser.parse(source),
      printHighlighter,
      (text, classes) =>
        out.push(classes ? `<span class="${classes}">${escape(text)}</span>` : escape(text)),
      () => out.push('\n')
    )
    code.innerHTML = out.join('')
    block.classList.add('md-code--lit')
  }
}
